<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        $defaults = [
            // Feature toggles (super_admin only)
            'feature_link_predecessor'  => 'true',
            'feature_legacy_case'       => 'true',
            'feature_existing_client'   => 'true',

            // Configurable dropdowns (stored as JSON)
            'dropdown_service_codes' => json_encode([
                ["code"=>"PAS",  "label"=>"PAS – Prior Art Search"],
                ["code"=>"PRV",  "label"=>"PRV – Provisional Application Filing"],
                ["code"=>"CPT",  "label"=>"CPT – Complete Application Filing"],
                ["code"=>"NPA",  "label"=>"NPA – National Phase Entry"],
                ["code"=>"DFT",  "label"=>"DFT – Patent Drafting"],
                ["code"=>"FIL",  "label"=>"FIL – Patent Filing (General)"],
                ["code"=>"PCT",  "label"=>"PCT – PCT International Filing"],
                ["code"=>"NPE",  "label"=>"NPE – National Phase Entry"],
                ["code"=>"DIV",  "label"=>"DIV – Divisional Application"],
                ["code"=>"CIP",  "label"=>"CIP – Continuation-in-Part"],
                ["code"=>"CON",  "label"=>"CON – Continuation Application"],
                ["code"=>"CNV",  "label"=>"CNV – Application Conversion"],
                ["code"=>"EXR",  "label"=>"EXR – Request for Examination"],
                ["code"=>"FER",  "label"=>"FER – First Examination Report Response"],
                ["code"=>"SER",  "label"=>"SER – Second Examination Report Response"],
                ["code"=>"TER",  "label"=>"TER – Third / Subsequent Exam Report Response"],
                ["code"=>"AMD",  "label"=>"AMD – Amendments to Specification / Claims"],
                ["code"=>"CAR",  "label"=>"CAR – Counter-Arguments / Written Submissions"],
                ["code"=>"OBJ",  "label"=>"OBJ – Response to Objections"],
                ["code"=>"HRG",  "label"=>"HRG – Hearing Representation"],
                ["code"=>"PBL",  "label"=>"PBL – Publication Request"],
                ["code"=>"PGO",  "label"=>"PGO – Pre-Grant Opposition Filing"],
                ["code"=>"PGR",  "label"=>"PGR – Pre-Grant Opposition Response"],
                ["code"=>"GRT",  "label"=>"GRT – Grant / Acceptance"],
                ["code"=>"POG",  "label"=>"POG – Post-Grant Opposition Filing"],
                ["code"=>"POR",  "label"=>"POR – Post-Grant Opposition Response"],
                ["code"=>"APL",  "label"=>"APL – Appeal Filing"],
                ["code"=>"APR",  "label"=>"APR – Appeal Response / Arguments"],
                ["code"=>"REI",  "label"=>"REI – Reinstatement of Lapsed Patent"],
                ["code"=>"WTH",  "label"=>"WTH – Withdrawal / Abandonment"],
                ["code"=>"REN",  "label"=>"REN – Patent Renewal / Maintenance Fee"],
                ["code"=>"ANN",  "label"=>"ANN – Annual Fee / Annuity Management"],
                ["code"=>"LAP",  "label"=>"LAP – Revival of Lapsed Application"],
                ["code"=>"SRH",  "label"=>"SRH – Prior Art Search"],
                ["code"=>"PAT",  "label"=>"PAT – Patentability Opinion"],
                ["code"=>"FTO",  "label"=>"FTO – Freedom to Operate Study"],
                ["code"=>"VAL",  "label"=>"VAL – Validity / Invalidity Opinion"],
                ["code"=>"INF",  "label"=>"INF – Infringement Analysis"],
                ["code"=>"LND",  "label"=>"LND – Patent Landscape Study"],
                ["code"=>"AUD",  "label"=>"AUD – IP Portfolio Audit"],
                ["code"=>"INV",  "label"=>"INV – Invention Disclosure Review"],
                ["code"=>"LIC",  "label"=>"LIC – Licensing Agreement Drafting"],
                ["code"=>"ASG",  "label"=>"ASG – Assignment / Transfer Registration"],
                ["code"=>"CDL",  "label"=>"CDL – Compulsory Licence / Revocation"],
                ["code"=>"TRN",  "label"=>"TRN – Technology Transfer Agreement"],
                ["code"=>"IPR",  "label"=>"IPR – Inter Partes Review (USPTO)"],
                ["code"=>"RCE",  "label"=>"RCE – Request for Continued Examination"],
                ["code"=>"TMS",  "label"=>"TMS – Trademark Search"],
                ["code"=>"TMD",  "label"=>"TMD – Trademark Drafting / Advice"],
                ["code"=>"TMF",  "label"=>"TMF – Trademark Filing"],
                ["code"=>"TMC",  "label"=>"TMC – Trademark Multi-Class Filing"],
                ["code"=>"TME",  "label"=>"TME – TM Examination Report Response"],
                ["code"=>"TMJ",  "label"=>"TMJ – TM Journal / Gazette Monitoring"],
                ["code"=>"TMO",  "label"=>"TMO – TM Opposition Filing"],
                ["code"=>"TMOR", "label"=>"TMOR – TM Opposition Reply / Counter-Statement"],
                ["code"=>"TMH",  "label"=>"TMH – TM Hearing Representation"],
                ["code"=>"TMG",  "label"=>"TMG – TM Grant / Registration Certificate"],
                ["code"=>"TMRN", "label"=>"TMRN – Trademark Renewal"],
                ["code"=>"TMA",  "label"=>"TMA – TM Assignment / Transfer"],
                ["code"=>"TMWT", "label"=>"TMWT – Trademark Watch Service"],
                ["code"=>"TMINF","label"=>"TMINF – TM Infringement Notice / Action"],
                ["code"=>"TMMD", "label"=>"TMMD – Madrid Protocol / International TM Filing"],
                ["code"=>"DSF",  "label"=>"DSF – Design Registration Filing"],
                ["code"=>"DSE",  "label"=>"DSE – Design Examination Response"],
                ["code"=>"DSR",  "label"=>"DSR – Design Registration Certificate"],
                ["code"=>"DSN",  "label"=>"DSN – Design Renewal"],
                ["code"=>"DSA",  "label"=>"DSA – Design Assignment"],
                ["code"=>"CRF",  "label"=>"CRF – Copyright Registration Filing"],
                ["code"=>"CRL",  "label"=>"CRL – Copyright Licence Drafting"],
                ["code"=>"CRA",  "label"=>"CRA – Copyright Assignment"],
                ["code"=>"GIF",  "label"=>"GIF – GI Tag Application Filing"],
                ["code"=>"GIE",  "label"=>"GIE – GI Examination Response"],
                ["code"=>"GIR",  "label"=>"GIR – GI Registration"],
                ["code"=>"PVF",  "label"=>"PVF – Plant Variety Protection Filing"],
                ["code"=>"PVR",  "label"=>"PVR – Plant Variety Certificate"],
                ["code"=>"POA",  "label"=>"POA – Power of Attorney"],
                ["code"=>"NOT",  "label"=>"NOT – Notarization"],
                ["code"=>"LEG",  "label"=>"LEG – Legalization / Apostille"],
                ["code"=>"TRL",  "label"=>"TRL – Translation Services"],
                ["code"=>"CSL",  "label"=>"CSL – Legal Consultation / Advisory"],
                ["code"=>"STR",  "label"=>"STR – IP Strategy / Portfolio Review"],
                ["code"=>"RPT",  "label"=>"RPT – Status Report / Reporting"],
                ["code"=>"MED",  "label"=>"MED – Mediation Assistance"],
                ["code"=>"ARB",  "label"=>"ARB – Arbitration Support"],
                ["code"=>"LTG",  "label"=>"LTG – IP Litigation Support"],
                ["code"=>"CRT",  "label"=>"CRT – Court Filing / Representation"],
                ["code"=>"DUE",  "label"=>"DUE – Due Diligence"],
                ["code"=>"VAR",  "label"=>"VAR – Various / Miscellaneous"],
            ]),

            'dropdown_country_codes' => json_encode([
                ["code"=>"IN","label"=>"IN – India (IPO)"],
                ["code"=>"US","label"=>"US – United States (USPTO)"],
                ["code"=>"EP","label"=>"EP – European Patent Office (EPO)"],
                ["code"=>"WO","label"=>"WO – WIPO / PCT (International)"],
                ["code"=>"CN","label"=>"CN – China (CNIPA)"],
                ["code"=>"JP","label"=>"JP – Japan (JPO)"],
                ["code"=>"KR","label"=>"KR – South Korea (KIPO)"],
                ["code"=>"AU","label"=>"AU – Australia (IP Australia)"],
                ["code"=>"CA","label"=>"CA – Canada (CIPO)"],
                ["code"=>"GB","label"=>"GB – United Kingdom (UKIPO)"],
                ["code"=>"DE","label"=>"DE – Germany (DPMA)"],
                ["code"=>"FR","label"=>"FR – France (INPI)"],
                ["code"=>"RU","label"=>"RU – Russia (Rospatent)"],
                ["code"=>"BR","label"=>"BR – Brazil (INPI-BR)"],
                ["code"=>"MX","label"=>"MX – Mexico (IMPI)"],
                ["code"=>"SG","label"=>"SG – Singapore (IPOS)"],
                ["code"=>"HK","label"=>"HK – Hong Kong (HKIPO)"],
                ["code"=>"MY","label"=>"MY – Malaysia (MyIPO)"],
                ["code"=>"TH","label"=>"TH – Thailand (DIP)"],
                ["code"=>"ID","label"=>"ID – Indonesia (DGIP)"],
                ["code"=>"PH","label"=>"PH – Philippines (IPOPHL)"],
                ["code"=>"VN","label"=>"VN – Vietnam (NOIP)"],
                ["code"=>"ZA","label"=>"ZA – South Africa (CIPC)"],
                ["code"=>"NZ","label"=>"NZ – New Zealand (IPONZ)"],
                ["code"=>"IL","label"=>"IL – Israel (ILPO)"],
                ["code"=>"TR","label"=>"TR – Turkey (TPTO)"],
                ["code"=>"AE","label"=>"AE – United Arab Emirates (MOIAT)"],
                ["code"=>"SA","label"=>"SA – Saudi Arabia (SAIP)"],
                ["code"=>"EG","label"=>"EG – Egypt (EGPO)"],
                ["code"=>"NG","label"=>"NG – Nigeria (FIPO)"],
                ["code"=>"KE","label"=>"KE – Kenya (KEIPO)"],
                ["code"=>"MA","label"=>"MA – Morocco (OMPIC)"],
                ["code"=>"PK","label"=>"PK – Pakistan (IPO-Pakistan)"],
                ["code"=>"BD","label"=>"BD – Bangladesh (DPDT)"],
                ["code"=>"LK","label"=>"LK – Sri Lanka (NIPO)"],
                ["code"=>"CH","label"=>"CH – Switzerland (IGE/IPI)"],
                ["code"=>"SE","label"=>"SE – Sweden (PRV)"],
                ["code"=>"NO","label"=>"NO – Norway (NIPO)"],
                ["code"=>"DK","label"=>"DK – Denmark (DKPTO)"],
                ["code"=>"FI","label"=>"FI – Finland (PRH)"],
                ["code"=>"NL","label"=>"NL – Netherlands (RNLIP)"],
                ["code"=>"BE","label"=>"BE – Belgium (BOIP)"],
                ["code"=>"AT","label"=>"AT – Austria (OPA)"],
                ["code"=>"IT","label"=>"IT – Italy (UIBM)"],
                ["code"=>"ES","label"=>"ES – Spain (OEPM)"],
                ["code"=>"PT","label"=>"PT – Portugal (INPI-PT)"],
                ["code"=>"PL","label"=>"PL – Poland (PPO)"],
            ]),
        ];

        foreach ($defaults as $key => $value) {
            DB::table('system_settings')->updateOrInsert(
                ['key' => $key],
                ['value' => $value, 'created_at' => $now, 'updated_at' => $now]
            );
        }
    }

    public function down(): void
    {
        DB::table('system_settings')->whereIn('key', [
            'feature_link_predecessor', 'feature_legacy_case', 'feature_existing_client',
            'dropdown_service_codes', 'dropdown_country_codes',
        ])->delete();
    }
};
