/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DiscussionsRouteImport } from './routes/discussions'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HrmsIndexRouteImport } from './routes/hrms/index'
import { Route as HrmsRecruitmentRouteImport } from './routes/hrms/recruitment'
import { Route as HrmsPerformanceRouteImport } from './routes/hrms/performance'
import { Route as HrmsPayrollRouteImport } from './routes/hrms/payroll'
import { Route as HrmsOffboardingRouteImport } from './routes/hrms/offboarding'
import { Route as HrmsLeaveRouteImport } from './routes/hrms/leave'
import { Route as HrmsEmployeesRouteImport } from './routes/hrms/employees'
import { Route as HrmsAttendanceRouteImport } from './routes/hrms/attendance'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsRoute = DiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsIndexRoute = HrmsIndexRouteImport.update({
  id: '/hrms/',
  path: '/hrms/',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsRecruitmentRoute = HrmsRecruitmentRouteImport.update({
  id: '/hrms/recruitment',
  path: '/hrms/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsPerformanceRoute = HrmsPerformanceRouteImport.update({
  id: '/hrms/performance',
  path: '/hrms/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsPayrollRoute = HrmsPayrollRouteImport.update({
  id: '/hrms/payroll',
  path: '/hrms/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsOffboardingRoute = HrmsOffboardingRouteImport.update({
  id: '/hrms/offboarding',
  path: '/hrms/offboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsLeaveRoute = HrmsLeaveRouteImport.update({
  id: '/hrms/leave',
  path: '/hrms/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsEmployeesRoute = HrmsEmployeesRouteImport.update({
  id: '/hrms/employees',
  path: '/hrms/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsAttendanceRoute = HrmsAttendanceRouteImport.update({
  id: '/hrms/attendance',
  path: '/hrms/attendance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/bulk': typeof BulkRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/compliance': typeof ComplianceRoute
  '/discussions': typeof DiscussionsRoute
  '/documents': typeof DocumentsRoute
  '/feedback': typeof FeedbackRoute
  '/financial': typeof FinancialRoute
  '/integrations': typeof IntegrationsRoute
  '/kanban': typeof KanbanRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRoute
  '/projects': typeof ProjectsRoute
  '/reminders': typeof RemindersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/timeline': typeof TimelineRoute
  '/tracker': typeof TrackerRoute
  '/hrms/attendance': typeof HrmsAttendanceRoute
  '/hrms/employees': typeof HrmsEmployeesRoute
  '/hrms/leave': typeof HrmsLeaveRoute
  '/hrms/offboarding': typeof HrmsOffboardingRoute
  '/hrms/payroll': typeof HrmsPayrollRoute
  '/hrms/performance': typeof HrmsPerformanceRoute
  '/hrms/recruitment': typeof HrmsRecruitmentRoute
  '/hrms/': typeof HrmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/bulk': typeof BulkRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/compliance': typeof ComplianceRoute
  '/discussions': typeof DiscussionsRoute
  '/documents': typeof DocumentsRoute
  '/feedback': typeof FeedbackRoute
  '/financial': typeof FinancialRoute
  '/integrations': typeof IntegrationsRoute
  '/kanban': typeof KanbanRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRoute
  '/projects': typeof ProjectsRoute
  '/reminders': typeof RemindersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/timeline': typeof TimelineRoute
  '/tracker': typeof TrackerRoute
  '/hrms/attendance': typeof HrmsAttendanceRoute
  '/hrms/employees': typeof HrmsEmployeesRoute
  '/hrms/leave': typeof HrmsLeaveRoute
  '/hrms/offboarding': typeof HrmsOffboardingRoute
  '/hrms/payroll': typeof HrmsPayrollRoute
  '/hrms/performance': typeof HrmsPerformanceRoute
  '/hrms/recruitment': typeof HrmsRecruitmentRoute
  '/hrms': typeof HrmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/bulk': typeof BulkRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/compliance': typeof ComplianceRoute
  '/discussions': typeof DiscussionsRoute
  '/documents': typeof DocumentsRoute
  '/feedback': typeof FeedbackRoute
  '/financial': typeof FinancialRoute
  '/integrations': typeof IntegrationsRoute
  '/kanban': typeof KanbanRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRoute
  '/projects': typeof ProjectsRoute
  '/reminders': typeof RemindersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/timeline': typeof TimelineRoute
  '/tracker': typeof TrackerRoute
  '/hrms/attendance': typeof HrmsAttendanceRoute
  '/hrms/employees': typeof HrmsEmployeesRoute
  '/hrms/leave': typeof HrmsLeaveRoute
  '/hrms/offboarding': typeof HrmsOffboardingRoute
  '/hrms/payroll': typeof HrmsPayrollRoute
  '/hrms/performance': typeof HrmsPerformanceRoute
  '/hrms/recruitment': typeof HrmsRecruitmentRoute
  '/hrms/': typeof HrmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/analytics'
    | '/approvals'
    | '/bulk'
    | '/calendar'
    | '/clients'
    | '/compliance'
    | '/discussions'
    | '/documents'
    | '/feedback'
    | '/financial'
    | '/integrations'
    | '/kanban'
    | '/notifications'
    | '/portal'
    | '/projects'
    | '/reminders'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/timeline'
    | '/tracker'
    | '/hrms/attendance'
    | '/hrms/employees'
    | '/hrms/leave'
    | '/hrms/offboarding'
    | '/hrms/payroll'
    | '/hrms/performance'
    | '/hrms/recruitment'
    | '/hrms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/analytics'
    | '/approvals'
    | '/bulk'
    | '/calendar'
    | '/clients'
    | '/compliance'
    | '/discussions'
    | '/documents'
    | '/feedback'
    | '/financial'
    | '/integrations'
    | '/kanban'
    | '/notifications'
    | '/portal'
    | '/projects'
    | '/reminders'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/timeline'
    | '/tracker'
    | '/hrms/attendance'
    | '/hrms/employees'
    | '/hrms/leave'
    | '/hrms/offboarding'
    | '/hrms/payroll'
    | '/hrms/performance'
    | '/hrms/recruitment'
    | '/hrms'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/analytics'
    | '/approvals'
    | '/bulk'
    | '/calendar'
    | '/clients'
    | '/compliance'
    | '/discussions'
    | '/documents'
    | '/feedback'
    | '/financial'
    | '/integrations'
    | '/kanban'
    | '/notifications'
    | '/portal'
    | '/projects'
    | '/reminders'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/timeline'
    | '/tracker'
    | '/hrms/attendance'
    | '/hrms/employees'
    | '/hrms/leave'
    | '/hrms/offboarding'
    | '/hrms/payroll'
    | '/hrms/performance'
    | '/hrms/recruitment'
    | '/hrms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BulkRoute: typeof BulkRoute
  CalendarRoute: typeof CalendarRoute
  ClientsRoute: typeof ClientsRoute
  ComplianceRoute: typeof ComplianceRoute
  DiscussionsRoute: typeof DiscussionsRoute
  DocumentsRoute: typeof DocumentsRoute
  FeedbackRoute: typeof FeedbackRoute
  FinancialRoute: typeof FinancialRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KanbanRoute: typeof KanbanRoute
  NotificationsRoute: typeof NotificationsRoute
  PortalRoute: typeof PortalRoute
  ProjectsRoute: typeof ProjectsRoute
  RemindersRoute: typeof RemindersRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  TimelineRoute: typeof TimelineRoute
  TrackerRoute: typeof TrackerRoute
  HrmsAttendanceRoute: typeof HrmsAttendanceRoute
  HrmsEmployeesRoute: typeof HrmsEmployeesRoute
  HrmsLeaveRoute: typeof HrmsLeaveRoute
  HrmsOffboardingRoute: typeof HrmsOffboardingRoute
  HrmsPayrollRoute: typeof HrmsPayrollRoute
  HrmsPerformanceRoute: typeof HrmsPerformanceRoute
  HrmsRecruitmentRoute: typeof HrmsRecruitmentRoute
  HrmsIndexRoute: typeof HrmsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions': {
      id: '/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof DiscussionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms/': {
      id: '/hrms/'
      path: '/hrms'
      fullPath: '/hrms/'
      preLoaderRoute: typeof HrmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms/recruitment': {
      id: '/hrms/recruitment'
      path: '/hrms/recruitment'
      fullPath: '/hrms/recruitment'
      preLoaderRoute: typeof HrmsRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms/performance': {
      id: '/hrms/performance'
      path: '/hrms/performance'
      fullPath: '/hrms/performance'
      preLoaderRoute: typeof HrmsPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms/payroll': {
      id: '/hrms/payroll'
      path: '/hrms/payroll'
      fullPath: '/hrms/payroll'
      preLoaderRoute: typeof HrmsPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms/offboarding': {
      id: '/hrms/offboarding'
      path: '/hrms/offboarding'
      fullPath: '/hrms/offboarding'
      preLoaderRoute: typeof HrmsOffboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms/leave': {
      id: '/hrms/leave'
      path: '/hrms/leave'
      fullPath: '/hrms/leave'
      preLoaderRoute: typeof HrmsLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms/employees': {
      id: '/hrms/employees'
      path: '/hrms/employees'
      fullPath: '/hrms/employees'
      preLoaderRoute: typeof HrmsEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms/attendance': {
      id: '/hrms/attendance'
      path: '/hrms/attendance'
      fullPath: '/hrms/attendance'
      preLoaderRoute: typeof HrmsAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  BulkRoute: BulkRoute,
  CalendarRoute: CalendarRoute,
  ClientsRoute: ClientsRoute,
  ComplianceRoute: ComplianceRoute,
  DiscussionsRoute: DiscussionsRoute,
  DocumentsRoute: DocumentsRoute,
  FeedbackRoute: FeedbackRoute,
  FinancialRoute: FinancialRoute,
  IntegrationsRoute: IntegrationsRoute,
  KanbanRoute: KanbanRoute,
  NotificationsRoute: NotificationsRoute,
  PortalRoute: PortalRoute,
  ProjectsRoute: ProjectsRoute,
  RemindersRoute: RemindersRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  TimelineRoute: TimelineRoute,
  TrackerRoute: TrackerRoute,
  HrmsAttendanceRoute: HrmsAttendanceRoute,
  HrmsEmployeesRoute: HrmsEmployeesRoute,
  HrmsLeaveRoute: HrmsLeaveRoute,
  HrmsOffboardingRoute: HrmsOffboardingRoute,
  HrmsPayrollRoute: HrmsPayrollRoute,
  HrmsPerformanceRoute: HrmsPerformanceRoute,
  HrmsRecruitmentRoute: HrmsRecruitmentRoute,
  HrmsIndexRoute: HrmsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
